# Generated by Django 4.1.7 on 2023-04-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0002_livro_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
    ]
