# Generated by Django 4.1.7 on 2023-04-11 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0003_remove_livro_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='livraria.autor'),
            preserve_default=False,
        ),
    ]
